### PR TITLE
Implement semaphore

### LINKED ISSUE #14: Flag Semaphore - Tests
- [x] All individual animations, letters (upper and lowercase), numbers, and spaces
- [x] Begin ("Attention") and end ("Ready to receive")
- [x] "Numbers to follow" and "Letters to follow" when appropriate
- [ ] Reject invalid strings

### PR DESCRIPTION
**Pull request by halyngoc**
This is a major rewrite of the library. _Don't merge! It's not ready yet._

Includes changes from PRs #21 and #23.
Closes #14.

Major changes include:
- All functions are now part of a class. Posing KHR_1 can now be done indirectly through Pose and Animation
- The [standard](https://github.com/pdx-robotics/Arduino_KHR-1/blob/18b5b9b0f4ce58fe2b44116ec818706db2cfccfc/Servo%20Direction%20Map.txt) has been implemented in Pose. This is to make animating KHR_1 easier by using a more intuitive mapping of the servo
- Leg servos can also be controlled using the standard
- All semaphore animations, including numbers and relevant cues have been added. But more testing need to be done (#14)

To-do:
- ~~Modify [SerialWrite_Semaphore.ino](https://github.com/pdx-robotics/Arduino_KHR-1/blob/18b5b9b0f4ce58fe2b44116ec818706db2cfccfc/examples/SerialWrite_Semaphore/SerialWrite_Semaphore.ino) and make that the main semaphore sketch~~
- ~~Change the order of Pose's members. Currently the order is left arm, left leg, right arm, right leg. I want to change it to left arm, right arm, left leg, right leg to make it more readable~~ _Moved to #38_
- [x] Change all the #define macros to static const int or inline functions and move them into the class

### CODE REVIEW

**Comment by halyngoc** [comment]
I noticed that [SerialWrite_Semaphore.ino](https://github.com/pdx-robotics/Arduino_KHR-1/pull/25/files#diff-4a7114d9d840080fd9e796175bb7e251) and [speed_test.ino](https://github.com/pdx-robotics/Arduino_KHR-1/pull/25/files#diff-b9c215fd8f81429844241a3ddccccf43) (not sure if we even need this sketch anymore) still uses the old VarSpeedServo. Will fix.

**Comment by geoolson** [comment]
speed_test.ino could be archived or removed. The VarSpeedServo library isn't being used for KHR1

**Comment by halyngoc** [comment]
I've noticed that master is too outdated compared to this branch which makes working on other issues more difficult. So I'll look into getting this merged as soon as possible. Some of these tasks in the to do list above are not essential and could be turned into separate issues after merging.

**Comment by halyngoc** [comment]
> - [ ] Change the order of Pose's members. Currently the order is left arm, left leg, right arm, right leg. I want to change it to left arm, right arm, left leg, right leg to make it more readable

Imo, we'll do some testing (#14), then I push the code for this task, then more testing and we're ready to merge. The rest can be done later.

**Comment by geoolson** [comment]
On line 125 in the header, pwm is initialized. Declare pwm in your header but initialize it in the constructor in the cpp. The init function is unnecessary as well. Move the body of your init function into the constructor of your cpp.

**Comment by halyngoc** [comment]
> The init function is unnecessary as well. Move the body of your init function into the constructor of your cpp.

As i remember, there used to be attach() calls in the constructor with created #3. Had to move them out in a separate attach() function, which then got replaced by this init(). Idk if the problem is still there but I don't wanna risk it.

**Comment by halyngoc** [comment]
> On line 125 in the header, pwm is initialized. Declare pwm in your header but initialize it in the constructor in the cpp.

As for this, idk how that escaped me 😃

**Comment by williamVbrines** [comment]
I would say that semaphore has been **successfully implemented**, tests have been made on the semaphore program. If there are bugs or enhancements we feel that need to be added or fixed we can make a new branch. 
As to the conflicting files 
- rand_wave.ino
- lib/KHR_1.cpp
- lib/KHR_1.h
The conflicts were made by me adding documentation and accidentally working in the master. The documentation in these files are of no consequence if they get written over.

I feel like this branch has done what it has meant to and should be merged to the master.

**Comment by halyngoc** [comment]
I don't think attach() exists anymore so I changed it to init() but I'll open an issue on these files later.

**Pull request merged**
